# Generated by Django 4.1 on 2022-09-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordrecognition', '0004_imagedto_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedto',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
        migrations.DeleteModel(
            name='WordRecognition',
        ),
    ]
