# Generated by Django 4.1.2 on 2022-11-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordrecognition', '0005_alter_imagedto_image_delete_wordrecognition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedto',
            name='image',
            field=models.TextField(default=''),
        ),
    ]
